spring:
  datasource:
    url: jdbc:postgresql://postgres-inventory:5432/smartstock_inventory
    username: ${DB_USER:smartstock}
    password: ${DB_PASSWORD:smartstock}

  kafka:
    bootstrap-servers: kafka:9092

server:
  port: 8003

logging:
  level:
    root: INFO
    com.smartstock: INFO
  file:
    name: ""
