apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smartstock.fullname" . }}-config
  labels:
    {{- include "smartstock.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.springProfile | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafkaBootstrapServers | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.otelExporterOtlpEndpoint | quote }}
  LOKI_URL: {{ .Values.config.lokiUrl | quote }}
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: {{ .Values.config.tracingSamplingProbability | quote }}
